# name: Run Weather Python Script

# on: [push]

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: 3.13

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Run script
#         env:
#           CLAUDE_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
#         run: python main.py

